version: 2
jobs:
 nlp:
   machine: ubuntu-2004:202111-02
   resource_class: large
   parallelism: 4
   steps:
     - checkout
     - run:
           name: "Build NLP Container"
           command: |
            docker build -f Dockerfile.nlp -t cmzambranat/nlp:4.2.0 .
     - deploy:
           name: "Push to Docker Hub"
           command: |
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push cmzambranat/nlp:4.2.0
              fi
workflows:
   version: 2
   commit:
     jobs:
       - nlp
